#!/usr/bin/env python3

"Get OAuth credentials."

from credentials import creds, scopes, store
from oauth2client import client, tools

if __name__ == '__main__':

    if not creds or creds.invalid:
        flow = client.flow_from_clientsecrets('client_secret.json', scopes)
        tools.run_flow(flow, store)
    else:
        print('Already have credentials.')
